import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityManager, EntityRepository } from '@mikro-orm/postgresql';
import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { AdjustmentSource } from '../common/enums/adjustment-source.enum';
import { BudgetPeriod } from '../common/enums/budget-period.enum';
import { TransactionType } from '../common/enums/transactions-type.enum';
import { BudgetAdjustmentEntity } from '../DAL/entities/budget-adjustment.entity';
import { BudgetEntity } from '../DAL/entities/budget.entity';
import { CategoryEntity } from '../DAL/entities/category.entity';
import { MonthlyBudgetPlanEntity } from '../DAL/entities/monthly-budget-plan.entity';
import { UserEntity } from '../DAL/entities/user.entity';
import { ExtendBudgetRequest } from './DTO/request/extend-budget.request';
import { CategoryBudgetResponse } from './DTO/response/category-budget.response';

@Injectable()
export class BudgetService {
  constructor(
    @InjectRepository(BudgetEntity)
    private readonly budgetRepository: EntityRepository<BudgetEntity>,
    @InjectRepository(BudgetAdjustmentEntity)
    private readonly adjustmentRepository: EntityRepository<BudgetAdjustmentEntity>,
    @InjectRepository(MonthlyBudgetPlanEntity)
    private readonly planRepository: EntityRepository<MonthlyBudgetPlanEntity>,
    @InjectRepository(CategoryEntity)
    private readonly categoryRepository: EntityRepository<CategoryEntity>,
  ) {}

  // ─── Get current month budget for category ──────────────────────────

  public async getCategoryCurrentBudget(
    categoryId: number,
    userId: number,
  ): Promise<CategoryBudgetResponse> {
    const category = await this.categoryRepository.findOne({
      id: categoryId,
      user: { id: userId },
    });

    if (!category) {
      throw new NotFoundException('Category not found');
    }

    if (category.transactionType !== TransactionType.EXPENSE) {
      throw new BadRequestException(
        'Only EXPENSE categories can have a budget',
      );
    }

    const currentMonth = this.normalizeToFirstOfMonth(new Date());

    const budget = await this.budgetRepository.findOne({
      category: { id: categoryId },
      period: BudgetPeriod.MONTHLY,
      month: currentMonth,
      isActive: true,
    });

    if (!budget) {
      throw new NotFoundException(
        'No active MONTHLY budget for this category in the current month',
      );
    }

    const collectedAmount = await this.computeCollectedAmount(
      categoryId,
      this.firstDayOfMonth(currentMonth),
      this.lastDayOfMonth(currentMonth),
    );

    const remaining = (
      parseFloat(budget.limitAmount) - parseFloat(collectedAmount)
    ).toFixed(2);

    const response = new CategoryBudgetResponse();
    response.budgetId = budget.id;
    response.categoryId = categoryId;
    response.period = budget.period;
    response.limitAmount = budget.limitAmount;
    response.collectedAmount = collectedAmount;
    response.remaining = remaining;
    response.isActive = budget.isActive;
    response.isAutoGenerated = budget.isAutoGenerated;
    return response;
  }

  // ─── Freeze / unfreeze ───────────────────────────────────────────────

  public async freezeBudget(budgetId: number, userId: number): Promise<void> {
    const budget = await this.findBudgetForUser(budgetId, userId);
    budget.isActive = false;
    await this.budgetRepository.getEntityManager().persist(budget).flush();
  }

  /** Negative available is allowed (surfaced as warning by frontend) */
  public async unfreezeBudget(budgetId: number, userId: number): Promise<void> {
    const budget = await this.findBudgetForUser(budgetId, userId);
    budget.isActive = true;
    await this.budgetRepository.getEntityManager().persist(budget).flush();
  }

  // ─── Extend budget limit ─────────────────────────────────────────────

  public async extendBudget(
    dto: ExtendBudgetRequest,
    userId: number,
  ): Promise<void> {
    const em = this.budgetRepository.getEntityManager();

    await em.transactional(async (txEm) => {
      const targetBudget = await txEm.findOne(BudgetEntity, {
        id: dto.targetBudgetId,
        category: { user: { id: userId } },
      });
      if (!targetBudget) throw new NotFoundException('Target budget not found');

      const adjustment = new BudgetAdjustmentEntity(
        targetBudget,
        dto.amount,
        dto.source,
        undefined,
        dto.reason,
      );

      if (dto.source === AdjustmentSource.BUDGET_REALLOCATION) {
        if (!dto.sourceBudgetId) {
          throw new BadRequestException(
            'sourceBudgetId is required for BUDGET_REALLOCATION',
          );
        }
        const sourceBudget = await txEm.findOne(BudgetEntity, {
          id: dto.sourceBudgetId,
          category: { user: { id: userId } },
        });
        if (!sourceBudget)
          throw new NotFoundException('Source budget not found');

        // Compute current spend on source budget to validate the reallocation
        const currentMonth = this.normalizeToFirstOfMonth(new Date());
        const collected = await this.computeCollectedAmountWithEm(
          sourceBudget.category.id,
          this.firstDayOfMonth(currentMonth),
          this.lastDayOfMonth(currentMonth),
          txEm,
        );

        const newSourceLimit =
          parseFloat(sourceBudget.limitAmount) - parseFloat(dto.amount);
        if (newSourceLimit < parseFloat(collected)) {
          throw new BadRequestException(
            'Reallocation would push source budget limit below already-spent amount',
          );
        }

        sourceBudget.limitAmount = newSourceLimit.toFixed(2);
        txEm.persist(sourceBudget);
        adjustment.sourceBudget = sourceBudget;
      } else {
        // INCOME_INCREASE: expand the monthly plan's projectedIncome
        const month =
          targetBudget.month ?? this.normalizeToFirstOfMonth(new Date());
        let plan = await txEm.findOne(MonthlyBudgetPlanEntity, {
          user: { id: userId },
          month,
        });
        if (!plan) {
          const userRef = txEm.getReference(UserEntity, userId);
          plan = new MonthlyBudgetPlanEntity(
            userRef as UserEntity,
            month,
            '0.00',
          );
        }
        plan.projectedIncome = (
          parseFloat(plan.projectedIncome) + parseFloat(dto.amount)
        ).toFixed(2);
        txEm.persist(plan);
      }

      targetBudget.limitAmount = (
        parseFloat(targetBudget.limitAmount) + parseFloat(dto.amount)
      ).toFixed(2);

      txEm.persist(targetBudget);
      txEm.persist(adjustment);
    });
  }

  // ─── Freeze-and-reallocate ───────────────────────────────────────────

  public async freezeAndReallocate(
    fromBudgetId: number,
    toBudgetId: number,
    userId: number,
  ): Promise<void> {
    const em = this.budgetRepository.getEntityManager();

    await em.transactional(async (txEm) => {
      const fromBudget = await txEm.findOne(BudgetEntity, {
        id: fromBudgetId,
        category: { user: { id: userId } },
      });
      if (!fromBudget) throw new NotFoundException('Source budget not found');

      const toBudget = await txEm.findOne(BudgetEntity, {
        id: toBudgetId,
        category: { user: { id: userId } },
      });
      if (!toBudget) throw new NotFoundException('Target budget not found');

      const freedAmount = fromBudget.limitAmount;

      fromBudget.isActive = false;
      txEm.persist(fromBudget);

      toBudget.limitAmount = (
        parseFloat(toBudget.limitAmount) + parseFloat(freedAmount)
      ).toFixed(2);
      txEm.persist(toBudget);

      const adjustment = new BudgetAdjustmentEntity(
        toBudget,
        freedAmount,
        AdjustmentSource.INCOME_INCREASE,
        undefined,
        `Freed from frozen budget #${fromBudgetId}`,
      );
      txEm.persist(adjustment);
    });
  }

  // ─── Trigger generation for current month (manual endpoint) ─────────────
  // Exposed via controller POST /budget/generate

  // ─── Helpers ──────────────────────────────────────────────────────────────

  private async findBudgetForUser(
    budgetId: number,
    userId: number,
  ): Promise<BudgetEntity> {
    const budget = await this.budgetRepository.findOne(
      { id: budgetId, category: { user: { id: userId } } },
      { populate: ['category'] },
    );
    if (!budget) throw new NotFoundException('Budget not found');
    return budget;
  }

  private async computeCollectedAmount(
    categoryId: number,
    from: Date,
    to: Date,
  ): Promise<string> {
    const em =
      this.budgetRepository.getEntityManager() as unknown as EntityManager;
    return this.computeCollectedAmountWithEm(categoryId, from, to, em);
  }

  private async computeCollectedAmountWithEm(
    categoryId: number,
    from: Date,
    to: Date,
    em: EntityManager,
  ): Promise<string> {
    const conn = em.getConnection('read');
    const rows = await conn.execute<{ total: string }[]>(
      `SELECT COALESCE(SUM(amount), 0)::text as total
       FROM transaction_entity
       WHERE category_id = $1
         AND created_at >= $2
         AND created_at <= $3`,
      [categoryId, from, to],
      'all',
    );
    return parseFloat(rows[0]?.total ?? '0').toFixed(2);
  }

  private normalizeToFirstOfMonth(date: Date): Date {
    return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1));
  }

  private firstDayOfMonth(month: Date): Date {
    return new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth(), 1));
  }

  private lastDayOfMonth(month: Date): Date {
    return new Date(
      Date.UTC(
        month.getUTCFullYear(),
        month.getUTCMonth() + 1,
        0,
        23,
        59,
        59,
        999,
      ),
    );
  }
}
