import { InjectRepository } from '@mikro-orm/nestjs';
import { EntityManager, EntityRepository } from '@mikro-orm/postgresql';
import { Injectable } from '@nestjs/common';
import { BudgetPeriod } from '../common/enums/budget-period.enum';
import { TransactionType } from '../common/enums/transactions-type.enum';
import { BudgetEntity } from '../DAL/entities/budget.entity';
import { CategoryEntity } from '../DAL/entities/category.entity';
import { TransactionEntity } from '../DAL/entities/transaction.entity';
import { BudgetPlanService } from './budget-plan.service';

@Injectable()
export class BudgetGenerationService {
  constructor(
    @InjectRepository(CategoryEntity)
    private readonly categoryRepository: EntityRepository<CategoryEntity>,
    @InjectRepository(BudgetEntity)
    private readonly budgetRepository: EntityRepository<BudgetEntity>,
    @InjectRepository(TransactionEntity)
    private readonly transactionRepository: EntityRepository<TransactionEntity>,
    private readonly budgetPlanService: BudgetPlanService,
  ) {}

  /**
   * Generates MONTHLY budgets for all EXPENSE categories of a user
   * that don't yet have one for the given month.
   * Safe to call multiple times (idempotent per category+month).
   */
  public async generateForUserAndMonth(
    userId: number,
    month: Date,
  ): Promise<void> {
    const normalizedMonth = this.normalizeToFirstOfMonth(month);

    const categories = await this.categoryRepository.find({
      user: { id: userId },
      transactionType: TransactionType.EXPENSE,
    });

    const em = this.budgetRepository.getEntityManager();

    for (const category of categories) {
      const existing = await this.budgetRepository.findOne({
        category: { id: category.id },
        period: BudgetPeriod.MONTHLY,
        month: normalizedMonth,
      });

      if (existing) continue;

      const previousMonth = new Date(
        Date.UTC(
          normalizedMonth.getUTCFullYear(),
          normalizedMonth.getUTCMonth() - 1,
          1,
        ),
      );
      const suggestedLimit = await this.calculateSuggestedLimit(
        category.id,
        previousMonth,
      );

      const budget = new BudgetEntity(
        category,
        BudgetPeriod.MONTHLY,
        suggestedLimit,
        normalizedMonth,
        undefined,
        undefined,
        true, // isAutoGenerated
      );

      em.persist(budget);
    }

    await em.flush();

    // Ensure a MonthlyBudgetPlan exists for this user+month
    await this.budgetPlanService.getOrCreatePlan(userId, normalizedMonth);
  }

  /**
   * Isolated, swappable calculation of the suggested limit for a category.
   * Current placeholder: use previous month's total spend in this category.
   * Replace this method when the formula is finalized.
   */
  private async calculateSuggestedLimit(
    categoryId: number,
    previousMonth: Date,
  ): Promise<string> {
    const firstDay = new Date(
      Date.UTC(previousMonth.getUTCFullYear(), previousMonth.getUTCMonth(), 1),
    );
    const lastDay = new Date(
      Date.UTC(
        previousMonth.getUTCFullYear(),
        previousMonth.getUTCMonth() + 1,
        0,
        23,
        59,
        59,
        999,
      ),
    );

    const em =
      this.transactionRepository.getEntityManager() as unknown as EntityManager;
    const conn = em.getConnection('read');

    const rows = await conn.execute<{ total: string }[]>(
      `SELECT COALESCE(SUM(amount), 0)::text as total
       FROM transaction_entity
       WHERE category_id = $1
         AND created_at >= $2
         AND created_at <= $3`,
      [categoryId, firstDay, lastDay],
      'all',
    );

    return parseFloat(rows[0]?.total ?? '0').toFixed(2);
  }

  private normalizeToFirstOfMonth(date: Date): Date {
    return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1));
  }
}
