import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { BudgetPeriod } from '../../../common/enums/budget-period.enum';

export class BudgetResponse {
  @ApiProperty({ example: 1 })
  id!: number;

  @ApiProperty({ example: 3 })
  categoryId!: number;

  @ApiProperty({ enum: BudgetPeriod, example: BudgetPeriod.MONTHLY })
  period!: BudgetPeriod;

  @ApiProperty({ example: '15000.00' })
  limitAmount!: string;

  @ApiProperty({ example: true })
  isActive!: boolean;

  @ApiProperty({ example: false })
  isAutoGenerated!: boolean;

  @ApiPropertyOptional({ example: '2026-07-01', nullable: true })
  month?: Date;

  @ApiPropertyOptional({ example: '2026-07-01', nullable: true })
  startDate?: Date;

  @ApiPropertyOptional({ example: '2026-07-31', nullable: true })
  endDate?: Date;

  @ApiProperty({ example: '2026-07-01T00:00:00.000Z', format: 'date-time' })
  createdAt!: Date;

  @ApiProperty({ example: '2026-07-01T00:00:00.000Z', format: 'date-time' })
  updatedAt!: Date;
}
