import { ApiProperty } from '@nestjs/swagger';
import { BudgetPeriod } from '../../../common/enums/budget-period.enum';

export class CategoryBudgetResponse {
  @ApiProperty({ example: 1 })
  budgetId!: number;

  @ApiProperty({ example: 3 })
  categoryId!: number;

  @ApiProperty({ enum: BudgetPeriod, example: BudgetPeriod.MONTHLY })
  period!: BudgetPeriod;

  @ApiProperty({ example: '15000.00', description: 'Budget limit' })
  limitAmount!: string;

  @ApiProperty({
    example: '8500.00',
    description: 'Total spent in the period (computed)',
  })
  collectedAmount!: string;

  @ApiProperty({
    example: '6500.00',
    description: 'limitAmount - collectedAmount',
  })
  remaining!: string;

  @ApiProperty({ example: true })
  isActive!: boolean;

  @ApiProperty({ example: false })
  isAutoGenerated!: boolean;
}
