import { Entity, Enum, ManyToOne, Property } from '@mikro-orm/core';
import { BudgetPeriod } from '../../common/enums/budget-period.enum';
import { BaseEntity } from './base.entity';
import { CategoryEntity } from './category.entity';

@Entity()
export class BudgetEntity extends BaseEntity {
  /** No deleteRule → RESTRICT: category deletion fails if active budget exists */
  @ManyToOne(() => CategoryEntity)
  category: CategoryEntity;

  @Enum(() => BudgetPeriod)
  period: BudgetPeriod;

  /** Stored as decimal(12,2). pg driver returns decimals as strings. */
  @Property({ columnType: 'decimal(12,2)' })
  limitAmount: string;

  /** Only for CUSTOM period */
  @Property({ columnType: 'date', nullable: true })
  startDate?: Date;

  /** Only for CUSTOM period; null = open-ended */
  @Property({ columnType: 'date', nullable: true })
  endDate?: Date;

  @Property({ default: true })
  isActive: boolean = true;

  @Property({ default: false })
  isAutoGenerated: boolean = false;

  /** Normalized to 1st of month; only for MONTHLY budgets */
  @Property({ columnType: 'date', nullable: true })
  month?: Date;

  constructor(
    category: CategoryEntity,
    period: BudgetPeriod,
    limitAmount: string,
    month?: Date,
    startDate?: Date,
    endDate?: Date,
    isAutoGenerated = false,
  ) {
    super();
    this.category = category;
    this.period = period;
    this.limitAmount = limitAmount;
    this.month = month;
    this.startDate = startDate;
    this.endDate = endDate;
    this.isAutoGenerated = isAutoGenerated;
  }
}
